# ============================================================
# FYP - Medical Document Analysis
# patterns.py - All regex patterns for field extraction
# Student: Ayesha Sohail (U2386691)
# ============================================================

CBC_PATTERNS = {
    "Haemoglobin": [
        # Existing patterns
        r"HAEMOGLOBIN\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]\b",
        r"HEMOGLOBIN\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]\b",
        r"H[ae]moglobin\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]\*+",
        r"H[Aa][Ee][Mm][Oo][Gg][Ll][Oo][Bb][Ii][Nn]\s*[:\-]\s*(\d+\.?\d*)",
        r"(?<!\w)Hb\s*[:\-]\s*(\d+\.?\d*)",
        r"HGB\s*[:\-]\s*(\d+\.?\d*)",
        r"HAEMOGLOBIN\s*(?:\([^)]*\))?\s+(\d+\.?\d*)",
        r"HEMOGLOBIN\s*(?:\([^)]*\))?\s+(\d+\.?\d*)",
        # Worldwide formats
        r"Hgb\s*[:\-]\s*(\d+\.?\d*)",
        r"HB\s*[:\-]\s*(\d+\.?\d*)",
        r"Haemoglobin\s*\(Hb\)\s*[:\-]?\s*(\d+\.?\d*)",
        r"Hemoglobin\s*\(Hb\)\s*[:\-]?\s*(\d+\.?\d*)",
        r"Hb\s+(\d+\.?\d*)\s+[HLN]\b",
        r"HGB\s+(\d+\.?\d*)\s+[HLN]\b",
        r"Haemoglobin\s*Level\s*[:\-]\s*(\d+\.?\d*)",
        r"Hemoglobin\s*Level\s*[:\-]\s*(\d+\.?\d*)",
    ],
    "RBC": [
        # Existing patterns
        r"(?:TOTAL\s*)?RBC\s*(?:COUNT)?\s*[:\-]\s*(\d+\.?\d*)",
        r"Red\s*Blood\s*C(?:ell|ount)\s*[:\-]\s*(\d+\.?\d*)",
        r"Red\s*Blood\s*Cell\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]\*+",
        r"Red\s*Blood\s*Cell\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]",
        r"Red\s*Blood\s*Cell\s*(?:\([^)]*\))?\s+(\d+\.?\d*)",
        r"(?:TOTAL\s*)?RBC\s*(?:COUNT)?\s+(\d+\.?\d*)\s+[HLN]",
        r"(?:TOTAL\s*)?RBC\s*(?:COUNT)?\s+(\d+\.?\d*)",
        r"Erythrocytes?\s+(\d+\.?\d*)\s+[HLN]",
        # Worldwide formats
        r"RBC\s*Count\s*[:\-]\s*(\d+\.?\d*)",
        r"Red\s*Cell\s*Count\s*[:\-]\s*(\d+\.?\d*)",
        r"Erythrocyte\s*Count\s*[:\-]\s*(\d+\.?\d*)",
        r"Erythrocytes?\s*[:\-]\s*(\d+\.?\d*)",
        r"RBC\s*\(10\^6/[Uu][Ll]\)\s*[:\-]?\s*(\d+\.?\d*)",
        r"Red\s*Blood\s*Corpuscles\s*[:\-]\s*(\d+\.?\d*)",
    ],
    "PCV_HCT": [
        # Existing patterns
        r"(?:PCV|HCT|Haematocrit|Hematocrit)\s*(?:[/\(][^)]*\))?\s*[:\-]\s*(\d+\.?\d*)",
        r"PACKED\s*CELL\s*VOLUME\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]",
        r"PACKED\s*CELL\s*VOLUME\s*(?:\([^)]*\))?\s+(\d+\.?\d*)",
        r"Hematocrit\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]\*+",
        r"Hematocrit\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]",
        r"Hematocrit\s*(?:\([^)]*\))?\s+(\d+\.?\d*)",
        r"PCV\s*\(HCT\)\s+(\d+\.?\d*)\s+[HLN]",
        r"PCV\s*\(HCT\)\s+(\d+\.?\d*)",
        r"(?:PCV|HCT)\s+(\d+\.?\d*)\s+[HLN]",
        r"(?:PCV|HCT)\s+(\d+\.?\d*)",
        # Worldwide formats
        r"Haematocrit\s*[:\-]\s*(\d+\.?\d*)",
        r"HCT\s*%\s*[:\-]\s*(\d+\.?\d*)",
        r"Packed\s*Cell\s*Vol\s*[:\-]\s*(\d+\.?\d*)",
        r"Crit\s*[:\-]\s*(\d+\.?\d*)",
        r"Hct\s*[:\-]\s*(\d+\.?\d*)",
    ],
    "MCV": [
        # Existing patterns
        r"MCV\s*[:\-]\s*(\d+\.?\d*)",
        r"Mean\s*(?:Cell|Corpuscular)\s*Volume\s*[:\-]\s*(\d+\.?\d*)",
        r"MEAN\s*C(?:ELL|ORPUSCULAR)\s*VOLUME\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]",
        r"MEAN\s*C(?:ELL|ORPUSCULAR)\s*VOLUME\s*(?:\([^)]*\))?\s+(\d+\.?\d*)",
        r"Mean\s*Cell\s*Volume\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]\*+",
        r"Mean\s*Cell\s*Volume\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]",
        r"Mean\s*Cell\s*Volume\s*(?:\([^)]*\))?\s+(\d+\.?\d*)",
        r"MCV\s+(\d+\.?\d*)\s+[HLN]",
        r"MCV\s+(\d+\.?\d*)",
        # Worldwide formats
        r"Mean\s*Corpuscular\s*Vol\s*[:\-]\s*(\d+\.?\d*)",
        r"MCV\s*\(fL\)\s*[:\-]?\s*(\d+\.?\d*)",
        r"Mean\s*Red\s*Cell\s*Volume\s*[:\-]\s*(\d+\.?\d*)",
    ],
    "MCH": [
        # Existing patterns
        r"(?<!\w)MCH\s*[:\-]\s*(\d+\.?\d*)",
        r"Mean\s*(?:Cell|Corpuscular)\s*H[ae]moglobin\s*[:\-]\s*(\d+\.?\d*)",
        r"Mean\s*Cell\s*H(?:emoglobin|b)\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]\*+",
        r"Mean\s*Cell\s*H(?:emoglobin|b)\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]",
        r"Mean\s*Cell\s*H(?:emoglobin|b)\s*(?:\([^)]*\))?\s+(\d+\.?\d*)",
        r"(?<!\w)MCH\s+I\s+(\d+\.?\d*)",
        r"(?<!\w)MCH\s+(\d+\.?\d*)\s+[HLN]",
        r"(?<!\w)MCH\s+(\d+\.?\d*)",
        # Worldwide formats
        r"MCH\s*\(pg\)\s*[:\-]?\s*(\d+\.?\d*)",
        r"Mean\s*Corpuscular\s*Hb\s*[:\-]\s*(\d+\.?\d*)",
        r"Mean\s*Cell\s*Haemoglobin\s*[:\-]\s*(\d+\.?\d*)",
    ],
    "MCHC": [
        # Existing patterns
        r"MCHC\s*[:\-]\s*(\d+\.?\d*)",
        r"Mean\s*(?:Cell|Corpuscular)\s*H[ae]moglobin\s*Conc(?:entration)?\s*[:\-]\s*(\d+\.?\d*)",
        r"Mean\s*Cell\s*Hb\s*Conc\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]\*+",
        r"Mean\s*Cell\s*Hb\s*Conc\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]",
        r"Mean\s*Cell\s*Hb\s*Conc\s*(?:\([^)]*\))?\s+(\d+\.?\d*)",
        r"MCHC\s+(\d+\.?\d*)\s+[HLN]",
        r"MCHC\s+(\d+\.?\d*)",
        # Worldwide formats
        r"MCHC\s*\(g/dL\)\s*[:\-]?\s*(\d+\.?\d*)",
        r"Mean\s*Corpuscular\s*Hb\s*Conc\s*[:\-]\s*(\d+\.?\d*)",
        r"Mean\s*Cell\s*Haemoglobin\s*Conc\s*[:\-]\s*(\d+\.?\d*)",
        r"Hb\s*Concentration\s*[:\-]\s*(\d+\.?\d*)",
    ],
    "RDW": [
        # Existing patterns
        r"RDW\s*[:\-]\s*(\d+\.?\d*)",
        r"Red\s*Cell\s*Dist(?:ribution)?\s*Width\s*[:\-]\s*(\d+\.?\d*)",
        r"RED\s*CELL\s*DISTRIBUTION\s*WIDTH\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]",
        r"RED\s*CELL\s*DISTRIBUTION\s*WIDTH\s*(?:\([^)]*\))?\s+(\d+\.?\d*)",
        r"Red\s*Cell\s*Dist\s*Width\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]\*+",
        r"Red\s*Cell\s*Dist\s*Width\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]",
        r"Red\s*Cell\s*Dist\s*Width\s*(?:\([^)]*\))?\s+(\d+\.?\d*)",
        r"RDW\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]",
        r"RDW\s*(?:\([^)]*\))?\s+(\d+\.?\d*)",
        r"RDW(?:-CV|-SD)?\s+(\d+\.?\d*)",
        # Worldwide formats
        r"RDW-CV\s*[:\-]\s*(\d+\.?\d*)",
        r"RDW-SD\s*[:\-]\s*(\d+\.?\d*)",
        r"Anisocytosis\s*Index\s*[:\-]\s*(\d+\.?\d*)",
        r"Red\s*Cell\s*Distribution\s*[:\-]\s*(\d+\.?\d*)",
    ],
    "WBC": [
        # Existing patterns
        r"(?:WBC|White\s*Blood\s*C(?:ell|ount))\s*[:\-]\s*(\d+\.?\d*)",
        r"(?:Total\s*)?Leucocytes?\s*[:\-]\s*(\d+\.?\d*)",
        r"TLC\s*[:\-]\s*(\d+\.?\d*)",
        r"White\s*Blood\s*Cell\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]\*+",
        r"White\s*Blood\s*Cell\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]",
        r"White\s*Blood\s*Cell\s*(?:\([^)]*\))?\s+(\d+\.?\d*)",
        r"(?:TOTAL\s*)?WBC\s*(?:COUNT)?\s+(\d+\.?\d*)\s+[HLN]",
        r"(?:TOTAL\s*)?WBC\s*(?:COUNT)?\s+(\d+\.?\d*)",
        r"WBC\s*\([^)]*\)\s+(\d+\.?\d*)\s+[HLN]",
        r"WBC\s*\([^)]*\)\s+(\d+\.?\d*)",
        r"(?:Total\s*)?Leucocytes?\s+(\d+\.?\d*)\s+[HLN]",
        # Worldwide formats
        r"Leukocytes?\s*[:\-]\s*(\d+\.?\d*)",
        r"Total\s*Leukocyte\s*Count\s*[:\-]\s*(\d+\.?\d*)",
        r"Total\s*White\s*Cell\s*Count\s*[:\-]\s*(\d+\.?\d*)",
        r"WCC\s*[:\-]\s*(\d+\.?\d*)",
        r"Total\s*WBC\s*[:\-]\s*(\d+\.?\d*)",
        r"White\s*Cell\s*Count\s*[:\-]\s*(\d+\.?\d*)",
    ],
    "Neutrophils": [
        # Existing patterns
        r"Neutrophils?\s*[:\-]\s*(\d+\.?\d*)",
        r"Neutrophil\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]",
        r"Neutrophil\s*(?:\([^)]*\))?\s+(\d+\.?\d*)",
        r"NEUTROPHILS?\s+(\d+\.?\d*)\s+[HLN]",
        r"NEUTROPHILS?\s+(\d+\.?\d*)",
        # Worldwide formats
        r"Abs\s*Neutrophil\s*[:\-]\s*(\d+\.?\d*)",
        r"Absolute\s*Neutrophil\s*[:\-]\s*(\d+\.?\d*)",
        r"Polymorphs?\s*[:\-]\s*(\d+\.?\d*)",
        r"Granulocytes?\s*[:\-]\s*(\d+\.?\d*)",
        r"NEUT\s*[:\-]\s*(\d+\.?\d*)",
        r"NEU\s+(\d+\.?\d*)\s+[HLN]\b",
        r"Segs?\s*[:\-]\s*(\d+\.?\d*)",
    ],
    "Lymphocytes": [
        # Existing patterns
        r"Lymphocytes?\s*[:\-]\s*(\d+\.?\d*)",
        r"Lymphocyte\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]",
        r"Lymphocyte\s*(?:\([^)]*\))?\s+(\d+\.?\d*)",
        r"LYMPHOCYTES?\s+(\d+\.?\d*)\s+[HLN]",
        r"LYMPHOCYTES?\s+(\d+\.?\d*)",
        # Worldwide formats
        r"Abs\s*Lymphocyte\s*[:\-]\s*(\d+\.?\d*)",
        r"Absolute\s*Lymphocyte\s*[:\-]\s*(\d+\.?\d*)",
        r"LYMPH\s*[:\-]\s*(\d+\.?\d*)",
        r"LYM\s+(\d+\.?\d*)\s+[HLN]\b",
        r"Lymph\s+(\d+\.?\d*)\s+[HLN]\b",
    ],
    "Platelets": [
        # Existing patterns
        r"Platelets?\s*(?:COUNT)?\s*[:\-]\s*(\d+\.?\d*)",
        r"PLT\s*[:\-]\s*(\d+\.?\d*)",
        r"PLATELET\s*COUNT\s+(\d+\.?\d*)\s+[HLN]",
        r"PLATELET\s*COUNT\s+(\d+\.?\d*)",
        r"Platelet\s*count\s+(\d+\.?\d*)\s+[HLN]",
        r"Platelet\s*count\s+(\d+\.?\d*)",
        r"Platelet\s*Count\s*\([^)]*\)\s+(\d+\.?\d*)\s+[HLN]",
        r"Platelet\s*Count\s*\([^)]*\)\s+(\d+\.?\d*)",
        r"Platelets?\s+(\d+\.?\d*)\s+[HLN]",
        r"PLT\s+(\d+\.?\d*)\s+[HLN]",
        # Worldwide formats
        r"Thrombocytes?\s*[:\-]\s*(\d+\.?\d*)",
        r"PLT\s*Count\s*[:\-]\s*(\d+\.?\d*)",
        r"Platelet\s*\(PLT\)\s*[:\-]?\s*(\d+\.?\d*)",
        r"PLT\s*\(10\^3/[Uu][Ll]\)\s*[:\-]?\s*(\d+\.?\d*)",
        r"BPC\s*[:\-]\s*(\d+\.?\d*)",
    ],
}

LFT_PATTERNS = {
    "ALT": [
        # Existing patterns
        r"ALT\s*[:\-]\s*(\d+\.?\d*)",
        r"SGPT\s*[:\-]\s*(\d+\.?\d*)",
        r"(?:SGPT|ALT)\s*/\s*(?:ALT|SGPT)\s+(\d+\.?\d*)\s+[HLN]",
        r"(?:SGPT|ALT)\s*/\s*(?:ALT|SGPT)\s+(\d+\.?\d*)",
        r"(?:SGPT|ALT)\s*/?\s*(?:ALT|SGPT)?\s*:\s*(\d+\.?\d*)",
        r"ALT\s*/?\s*SGPT\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+\*?[HLN]",
        r"ALT\s*/?\s*SGPT\s*(?:\([^)]*\))?\s+(\d+\.?\d*)",
        r"ALT\s*/?\s*SGPT\s*(?:\{[^}]*\})?\s+(\d+\.?\d*)\s+\*?[HLN]",
        r"ALT\s*/?\s*SGPT\s*(?:\{[^}]*\})?\s+(\d+\.?\d*)",
        r"ALT\s*(?:\{[^}]*\})?\s+(\d+\.?\d*)\s+\*?[HLN]",
        r"ALT\s*(?:\{[^}]*\})?\s+(\d+\.?\d*)",
        r"ALT\s*(?:/\s*SGPT)?\s+(\d+\.?\d*)\s+[HLN]",
        r"SGPT\s*(?:/\s*ALT)?\s+(\d+\.?\d*)\s+[HLN]",
        r"ALT\s+(\d+\.?\d*)",
        r"SGPT\s+(\d+\.?\d*)",
        r"ALANINE\s*TRANSAMINASE\s*(?:SGPT)?\s*(?:\([^)]*\))?\s+(?:PHOTOMETRY|CALCULATED|COLORIMETRY)?\s*(\d+\.?\d*)",
        r"ALANINE\s*AMINOTRANSFERASE\s*(?:\([^)]*\))?\s+(?:PHOTOMETRY|CALCULATED)?\s*(\d+\.?\d*)",
        # Worldwide formats
        r"Alanine\s*Transaminase\s*[:\-]\s*(\d+\.?\d*)",
        r"Alanine\s*Aminotransferase\s*[:\-]\s*(\d+\.?\d*)",
        r"GPT\s*[:\-]\s*(\d+\.?\d*)",
        r"ALT\s*\(SGPT\)\s*[:\-]?\s*(\d+\.?\d*)",
        r"SGPT\s*\(ALT\)\s*[:\-]?\s*(\d+\.?\d*)",
        r"Serum\s*ALT\s*[:\-]\s*(\d+\.?\d*)",
    ],
    "AST": [
        # Existing patterns
        r"AST\s*[:\-]\s*(\d+\.?\d*)",
        r"SGOT\s*[:\-]\s*(\d+\.?\d*)",
        r"(?:SGOT|AST)\s*/\s*(?:AST|SGOT)\s+(\d+\.?\d*)\s+[HLN]",
        r"(?:SGOT|AST)\s*/\s*(?:AST|SGOT)\s+(\d+\.?\d*)",
        r"(?:SGOT|AST)\s*/?\s*(?:AST|SGOT)?\s*:\s*(\d+\.?\d*)",
        r"AST\s*/?\s*SGOT\s*(?:\{[^}]*\})?\s+(\d+\.?\d*)\s+\*?[HLN]",
        r"AST\s*/?\s*SGOT\s*(?:\{[^}]*\})?\s+(\d+\.?\d*)",
        r"AST\s*(?:\{[^}]*\})?\s+(\d+\.?\d*)\s+\*?[HLN]",
        r"AST\s*(?:\{[^}]*\})?\s+(\d+\.?\d*)",
        r"AST\s*(?:/\s*SGOT)?\s+(\d+\.?\d*)\s+[HLN]",
        r"SGOT\s*(?:/\s*AST)?\s+(\d+\.?\d*)\s+[HLN]",
        r"AST\s+(\d+\.?\d*)",
        r"SGOT\s+(\d+\.?\d*)",
        r"ASPARTATE\s*AMINOTRANSFERASE\s*(?:SGOT)?\s*(?:\([^)]*\))?\s+(?:PHOTOMETRY|CALCULATED|COLORIMETRY)?\s*(\d+\.?\d*)",
        r"ASPARTATE\s*TRANSAMINASE\s*(?:\([^)]*\))?\s+(?:PHOTOMETRY|CALCULATED)?\s*(\d+\.?\d*)",
        # Worldwide formats
        r"Aspartate\s*Transaminase\s*[:\-]\s*(\d+\.?\d*)",
        r"Aspartate\s*Aminotransferase\s*[:\-]\s*(\d+\.?\d*)",
        r"GOT\s*[:\-]\s*(\d+\.?\d*)",
        r"AST\s*\(SGOT\)\s*[:\-]?\s*(\d+\.?\d*)",
        r"SGOT\s*\(AST\)\s*[:\-]?\s*(\d+\.?\d*)",
        r"Serum\s*AST\s*[:\-]\s*(\d+\.?\d*)",
    ],
    "Bilirubin_Total": [
        # Existing patterns
        r"(?:Total\s*)?Bilirubin\s*(?:Total)?\s*[:\-]\s*(\d+\.?\d*)",
        r"Total\s*Bilirubin\s*:\s*(\d+\.?\d*)",
        r"Bilirubin\s*Total\s*(?:\{[^}]*\})?\s+(\d+\.?\d*)\s+\*?[HLN]",
        r"Bilirubin\s*Total\s*(?:\{[^}]*\})?\s+(\d+\.?\d*)",
        r"Total\s*Bilirubin\s+(\d+\.?\d*)\s+\*?[HLN]",
        r"Total\s*Bilirubin\s+(\d+\.?\d*)",
        r"Bilirubin\s*[—\-]\s*Total\s+(\d+\.?\d*)\s+[HLN]",
        r"T\.?\s*Bili(?:rubin)?\s*[:\-]\s*(\d+\.?\d*)",
        r"Bilirubin\s+(\d+\.?\d*)\s+[HLN]",
        r"BILIRUBIN\s*[\-\s]*TOTAL\s+(?:PHOTOMETRY|CALCULATED|COLORIMETRY)?\s*(\d+\.?\d*)",
        r"BILIRUBIN,?\s*TOTAL\s+(?:PHOTOMETRY|CALCULATED)?\s*(\d+\.?\d*)",
        # Worldwide formats
        r"Serum\s*Bilirubin\s*(?:Total)?\s*[:\-]\s*(\d+\.?\d*)",
        r"S\.?\s*Bilirubin\s*(?:Total)?\s*[:\-]\s*(\d+\.?\d*)",
        r"TB\s*[:\-]\s*(\d+\.?\d*)",
        r"T-Bili\s*[:\-]\s*(\d+\.?\d*)",
        r"Bili\s*Total\s*[:\-]\s*(\d+\.?\d*)",
    ],
    "ALP": [
        # Existing patterns
        r"ALP\s*[:\-]\s*(\d+\.?\d*)",
        r"Alkaline\s*Phosphatase\s*[:\-]\s*(\d+\.?\d*)",
        r"Alkaline\s*Phosphatase\s*:\s*(\d+\.?\d*)",
        r"Alkaline\s*Phosphatase\s*(?:\{[^}]*\})?\s+(\d+\.?\d*)\s+\*?[HLN]",
        r"Alkaline\s*Phosphatase\s*(?:\{[^}]*\})?\s+(\d+\.?\d*)",
        r"Alkaline\s*Phosphatase\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]\b",
        r"ALP\s+(\d+\.?\d*)\s+[HLN]\b",
        r"Alkaline\s*Phosphatase\s*(?:\([^)]*\))?\s+(\d+\.?\d*)",
        r"ALP\s+(\d+\.?\d*)",
        r"ALKALINE\s*PHOSPHATASE\s+(?:PHOTOMETRY|CALCULATED|COLORIMETRY)?\s*(\d+\.?\d*)",
        r"ALKP\s+(?:PHOTOMETRY|CALCULATED)?\s*(\d+\.?\d*)",
        # Worldwide formats
        r"Alk\s*Phos\s*[:\-]\s*(\d+\.?\d*)",
        r"Alk\.\s*Phosphatase\s*[:\-]\s*(\d+\.?\d*)",
        r"ALKP\s*[:\-]\s*(\d+\.?\d*)",
        r"Serum\s*ALP\s*[:\-]\s*(\d+\.?\d*)",
        r"AP\s*[:\-]\s*(\d+\.?\d*)",
    ],
    "Albumin": [
        # Existing patterns
        r"Albumin\s*[:\-]\s*(\d+\.?\d*)",
        r"Albumin\s*:\s*(\d+\.?\d*)",
        r"Albumin\s*(?:\{[^}]*\})?\s+(\d+\.?\d*)\s+\*?[HLN]",
        r"Albumin\s*(?:\{[^}]*\})?\s+(\d+\.?\d*)",
        r"Albumin\s+(\d+\.?\d*)\s+[HLN]",
        r"Albumin\s+(\d+\.?\d*)",
        r"ALBUMIN\s*[\-\s]*SERUM\s+(?:PHOTOMETRY|CALCULATED|COLORIMETRY)?\s*(\d+\.?\d*)",
        r"SERUM\s*ALBUMIN\s+(?:PHOTOMETRY|CALCULATED)?\s*(\d+\.?\d*)",
        # Worldwide formats
        r"Serum\s*Albumin\s*[:\-]\s*(\d+\.?\d*)",
        r"S\.\s*Albumin\s*[:\-]\s*(\d+\.?\d*)",
        r"ALB\s*[:\-]\s*(\d+\.?\d*)",
        r"ALB\s+(\d+\.?\d*)\s+[HLN]\b",
    ],
    "GGT": [
        # Existing patterns
        r"GGT\s*[:\-]\s*(\d+\.?\d*)",
        r"Gamma\s*(?:GT|Glutamyl)\s*[:\-]\s*(\d+\.?\d*)",
        r"Gamma\s*Glutamyl\s*(?:Transferase)?\s*:\s*(\d+\.?\d*)",
        r"GGT\s*(?:\{[^}]*\})?\s+(\d+\.?\d*)\s+\*?[HLN]",
        r"GGT\s*(?:\{[^}]*\})?\s+(\d+\.?\d*)",
        r"Gamma\s*Glutamyl\s*(?:Transferase|Trans)?\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]\b",
        r"Gamma\s*GT\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]\b",
        r"GGT\s+(\d+\.?\d*)\s+[HLN]\b",
        r"Gamma\s*Glutamyl\s*(?:Transferase)?\s*(?:\([^)]*\))?\s+(\d+\.?\d*)",
        r"GGT\s+(\d+\.?\d*)",
        r"Gamma\s*GT\s+(\d+\.?\d*)",
        r"GAMMA\s*GLUTAMYL\s*TRANSFERASE\s*(?:GGT)?\s*(?:PHOTOMETRY|CALCULATED|COLORIMETRY)?\s*(\d+\.?\d*)",
        r"GAMMA\s*GT\s+(?:PHOTOMETRY|CALCULATED)?\s*(\d+\.?\d*)",
        # Worldwide formats
        r"γ-GT\s*[:\-]\s*(\d+\.?\d*)",
        r"GGTP\s*[:\-]\s*(\d+\.?\d*)",
        r"Serum\s*GGT\s*[:\-]\s*(\d+\.?\d*)",
        r"γGT\s*[:\-]\s*(\d+\.?\d*)",
    ],
}

RFT_PATTERNS = {
    "Creatinine": [
        # Existing patterns
        r"(?:Serum\s*)?Creatinine\s*[:\-]\s*(\d+\.?\d*)",
        r"SERUM\s*CREATININE\s+(\d+\.?\d*)",
        r"Creatinine\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[▲▼]?\s*[HLN]\b",
        r"Creatinine\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL|AH|VL|AL|VH)\b",
        r"Creatinine\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[AV][HL]\b",
        r"Creatinine\s+(\d+\.?\d*)",
        # Worldwide formats
        r"S\.\s*Creatinine\s*[:\-]\s*(\d+\.?\d*)",
        r"Creat\s*[:\-]\s*(\d+\.?\d*)",
        r"Crea\s*[:\-]\s*(\d+\.?\d*)",
        r"CREA\s+(\d+\.?\d*)\s+[HLN]\b",
        r"Creatinine\s*\(mg/dL\)\s*[:\-]?\s*(\d+\.?\d*)",
        r"Plasma\s*Creatinine\s*[:\-]\s*(\d+\.?\d*)",
    ],
    "Urea": [
        # Existing patterns
        r"(?:Blood\s*)?Urea\s*[:\-]\s*(\d+\.?\d*)",
        r"BUN\s*[:\-]\s*(\d+\.?\d*)",
        r"SERUM\s*UREA\s+(\d+\.?\d*)",
        r"(?:Blood\s*)?Urea\s+(\d+\.?\d*)\s+[▲▼]?\s*[HLN]\b",
        r"BUN\s+(\d+\.?\d*)\s+[▲▼]?\s*[HLN]\b",
        r"(?:Blood\s*)?Urea\s+(\d+\.?\d*)",
        # Worldwide formats
        r"S\.\s*Urea\s*[:\-]\s*(\d+\.?\d*)",
        r"Serum\s*Urea\s*[:\-]\s*(\d+\.?\d*)",
        r"Blood\s*Urea\s*Nitrogen\s*[:\-]\s*(\d+\.?\d*)",
        r"Urea\s*Nitrogen\s*[:\-]\s*(\d+\.?\d*)",
        r"UREA\s+(\d+\.?\d*)\s+[HLN]\b",
    ],
    "Uric_Acid": [
        # Existing patterns
        r"Uric\s*Acid\s*[:\-]\s*(\d+\.?\d*)",
        r"URIC\s*ACID\s+(\d+\.?\d*)",
        r"Uric\s*Acid\s+(\d+\.?\d*)\s+[▲▼]?\s*[HLN]\b",
        r"Uric\s*Acid\s+(\d+\.?\d*)",
        # Worldwide formats
        r"Serum\s*Uric\s*Acid\s*[:\-]\s*(\d+\.?\d*)",
        r"S\.\s*Uric\s*Acid\s*[:\-]\s*(\d+\.?\d*)",
        r"UA\s*[:\-]\s*(\d+\.?\d*)",
        r"Urate\s*[:\-]\s*(\d+\.?\d*)",
        r"Uricemia\s*[:\-]\s*(\d+\.?\d*)",
    ],
    "eGFR": [
        # Existing patterns
        r"eGFR\s*[:\-]\s*(\d+\.?\d*)",
        r"GFR\s*[:\-]\s*(\d+\.?\d*)",
        r"eGFR\s*\([^)]*\)\s+(\d+\.?\d*)\s+[▲▼]?\s*[HLN]\b",
        r"eGFR\s*\([^)]*\)\s+(\d+\.?\d*)",
        r"CKD.EPI[^:]*[:\-]?\s*(\d+\.?\d*)",
        r"eGFR\s+(\d+\.?\d*)\s+[▲▼]?\s*[HLN]\b",
        r"eGFR\s+(\d+\.?\d*)",
        # Worldwide formats
        r"Estimated\s*GFR\s*[:\-]\s*(\d+\.?\d*)",
        r"Glomerular\s*Filtration\s*Rate\s*[:\-]\s*(\d+\.?\d*)",
        r"MDRD\s*GFR\s*[:\-]\s*(\d+\.?\d*)",
        r"eGFR\s*\(CKD-EPI\)\s*[:\-]?\s*(\d+\.?\d*)",
    ],
    "Sodium": [
        # Existing patterns
        r"Sodium\s*(?:\([^)]*\))?\s*[:\-]\s*(\d+\.?\d*)",
        r"SODIUM\s*\([^)]*\)\s+(\d+\.?\d*)",
        r"Sodium\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[▲▼]?\s*[HLN]\b",
        r"Sodium\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[AV][HL_]\b",
        r"Sodium\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+V_L\b",
        r"Sodium\s+(\d+\.?\d*)",
        # Worldwide formats
        r"Na\s*[:\-]\s*(\d+\.?\d*)",
        r"Na\+\s*[:\-]\s*(\d+\.?\d*)",
        r"Serum\s*Sodium\s*[:\-]\s*(\d+\.?\d*)",
        r"S\.\s*Sodium\s*[:\-]\s*(\d+\.?\d*)",
        r"Na\s+(\d+\.?\d*)\s+[HLN]\b",
        r"Natrium\s*[:\-]\s*(\d+\.?\d*)",
    ],
    "Potassium": [
        # Existing patterns
        r"Potassium\s*(?:\([^)]*\))?\s*[:\-]\s*(\d+\.?\d*)",
        r"POTASSIUM\s*\([^)]*\)\s+(\d+\.?\d*)",
        r"Potassium\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[▲▼]?\s*[HLN]\b",
        r"Potassium\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[AV][HL_]\b",
        r"Potassium\s+(\d+\.?\d*)",
        # Worldwide formats
        r"K\s*[:\-]\s*(\d+\.?\d*)",
        r"K\+\s*[:\-]\s*(\d+\.?\d*)",
        r"Serum\s*Potassium\s*[:\-]\s*(\d+\.?\d*)",
        r"S\.\s*Potassium\s*[:\-]\s*(\d+\.?\d*)",
        r"K\s+(\d+\.?\d*)\s+[HLN]\b",
        r"Kalium\s*[:\-]\s*(\d+\.?\d*)",
    ],
}

BSG_PATTERNS = {
    "Fasting_Glucose": [
        # Existing patterns
        r"Fasting\s*Blood\s*Glucose\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s*\n",
        r"Fasting\s*(?:Blood\s*)?(?:Glucose|Sugar)\s*[:\-]\s*(\d+\.?\d*)",
        r"(?:FBS|FBG|FPG)\s*[:\-]\s*(\d+\.?\d*)",
        r"GLUCOSE,?\s*FASTING,?\s*(?:PLASMA)?\s*\n?\s*(\d+\.?\d*)",
        r"GLUCOSE,?\s*FASTING\s+(\d+\.?\d*)",
        r"BLOOD\s*SUGAR\s*FASTING\s+(\d+\.?\d*)",
        r"Fasting\s*Blood\s*Glucose\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL|BORDERLINE|Very\s*High|Very\s*Low|WITHIN[\s\S]{0,10}RANGE|ABOVE[\s\S]{0,10}RANGE)\b",
        r"Fasting\s*(?:Blood\s*)?(?:Glucose|Sugar)\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL|BORDERLINE|Very\s*High)\b",
        r"(?:FBS|FBG)\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL|BORDERLINE)\b",
        r"Fasting\s+(?:Glucose|Sugar)\s+(\d+\.?\d*)",
        # Worldwide formats
        r"Fasting\s*Plasma\s*Glucose\s*[:\-]\s*(\d+\.?\d*)",
        r"FPG\s*[:\-]\s*(\d+\.?\d*)",
        r"Glucose\s*Fasting\s*[:\-]\s*(\d+\.?\d*)",
        r"Fasting\s*Blood\s*Sugar\s*[:\-]\s*(\d+\.?\d*)",
        r"F\.?\s*Blood\s*Sugar\s*[:\-]\s*(\d+\.?\d*)",
        r"FBS\s+(\d+\.?\d*)\s+[HLN]\b",
        r"Glucose\s*Fasting\s*\(?P[il]asma\)?\s+(\d+\.?\d*)",
        r"Glucose\s*Fasting\s*\([^)]*\)\s+(\d+\.?\d*)",
        r"Glucose\s+Fasting\s+(\d+\.?\d*)",
    ],
    "Post_Prandial_Glucose": [
        # Existing patterns
        r"Post[\s\-]*Prandial\s*(?:Glucose|Sugar)?\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s*\n",
        r"Post\s*Prandial\s*(?:Glucose|Sugar)\s*[:\-]\s*(\d+\.?\d*)",
        r"(?:2hr?\s*)?PPG\s*[:\-]\s*(\d+\.?\d*)",
        r"PPBS\s*[:\-]\s*(\d+\.?\d*)",
        r"Post[\s\-]*Prandial\s*(?:Glucose|Sugar)?\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL|BORDERLINE|Very\s*High|WITHIN[\s\S]{0,10}RANGE|ABOVE[\s\S]{0,10}RANGE)\b",
        r"(?:PPG|PPBS)\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL|BORDERLINE)\b",
        r"Post\s*Prandial\s*(?:Glucose|Sugar)?\s+(\d+\.?\d*)",
        # Worldwide formats
        r"2\s*Hour\s*Post\s*Prandial\s*[:\-]\s*(\d+\.?\d*)",
        r"2hr\s*PP\s*[:\-]\s*(\d+\.?\d*)",
        r"2h\s*PG\s*[:\-]\s*(\d+\.?\d*)",
        r"Post\s*Meal\s*Glucose\s*[:\-]\s*(\d+\.?\d*)",
        r"After\s*Meal\s*(?:Glucose|Sugar)\s*[:\-]\s*(\d+\.?\d*)",
        r"PP\s*Blood\s*Sugar\s*[:\-]\s*(\d+\.?\d*)",
        r"Glucose\s*PP\s*\(?P[il]asma\)?\s+(\d+\.?\d*)",
        r"Glucose\s*PP\s*\([^)]*\)\s+(\d+\.?\d*)",
        r"Glucose\s+PP\s+(\d+\.?\d*)",
    ],
    "Random_Glucose": [
        # Existing patterns
        r"Random\s*Blood\s*(?:Sugar|Glucose)\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s*\n",
        r"Random\s*(?:Blood\s*)?(?:Sugar|Glucose)\s*[:\-]\s*(\d+\.?\d*)",
        r"(?:RBS|RBG|PPBS)\s*[:\-]\s*(\d+\.?\d*)",
        r"RANDOM\s*BLOOD\s*(?:GLUCOSE|SUGAR)\s+(\d+\.?\d*)\s*(?:mg|$)",
        r"Random\s*Blood\s*(?:Sugar|Glucose)\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL|BORDERLINE|Very\s*High|WITHIN[\s\S]{0,10}RANGE|ABOVE[\s\S]{0,10}RANGE)?\b",
        r"(?:RBS|RBG)\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL|BORDERLINE)\b",
        r"Random\s+(?:Glucose|Sugar)\s+(\d+\.?\d*)",
        r"RANDOM\s*BLOOD\s*GLUCOSE\s+(\d+\.?\d*)",
        # Worldwide formats
        r"Casual\s*Plasma\s*Glucose\s*[:\-]\s*(\d+\.?\d*)",
        r"Random\s*Plasma\s*Glucose\s*[:\-]\s*(\d+\.?\d*)",
        r"RBS\s+(\d+\.?\d*)\s+[HLN]\b",
        r"Glucose\s*Random\s*[:\-]\s*(\d+\.?\d*)",
        r"Blood\s*Glucose\s*Random\s*[:\-]\s*(\d+\.?\d*)",
    ],
    "HbA1c": [
        # Existing patterns
        r"HbA1c\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s*\n",
        r"HbA1c\s*[:\-]\s*(\d+\.?\d*)",
        r"HBA1C\s*[:\-]\s*(\d+\.?\d*)",
        r"Glycated\s*H(?:a)?emoglobin\s*[:\-]\s*(\d+\.?\d*)",
        r"HbA1c\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL|BORDERLINE|WITHIN[\s\S]{0,10}RANGE|ABOVE[\s\S]{0,10}RANGE)\b",
        r"HBA1C\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL|BORDERLINE)\b",
        r"HbA1c\s+(\d+\.?\d*)",
        # Worldwide formats
        r"Haemoglobin\s*A1c\s*[:\-]\s*(\d+\.?\d*)",
        r"Hemoglobin\s*A1c\s*[:\-]\s*(\d+\.?\d*)",
        r"Glycosylated\s*Hb\s*[:\-]\s*(\d+\.?\d*)",
        r"A1C\s*[:\-]\s*(\d+\.?\d*)",
        r"HbA\s*1c\s*[:\-]\s*(\d+\.?\d*)",
        r"Hb1Ac\s*[:\-]\s*(\d+\.?\d*)",
    ],
    "Fasting_Insulin": [
        # Existing patterns
        r"Fasting\s*Insulin\s*[:\-]\s*(\d+\.?\d*)",
        r"Fasting\s*Insulin\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL|BORDERLINE|WITHIN[\s\S]{0,10}RANGE)\b",
        r"Fasting\s*Insulin\s+(\d+\.?\d*)",
        r"Insulin\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL|BORDERLINE|WITHIN[\s\S]{0,10}RANGE)\b",
        # Worldwide formats
        r"Serum\s*Insulin\s*(?:Fasting)?\s*[:\-]\s*(\d+\.?\d*)",
        r"Insulin\s*Fasting\s*[:\-]\s*(\d+\.?\d*)",
        r"Fasting\s*Serum\s*Insulin\s*[:\-]\s*(\d+\.?\d*)",
        r"Basal\s*Insulin\s*[:\-]\s*(\d+\.?\d*)",
    ],
}

LIPID_PATTERNS = {
    "Total_Cholesterol": [
        # Existing patterns
        r"Total\s*Cholesterol\s*[:\-]\s*(\d+\.?\d*)",
        r"Total\s*Cholesterol\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL)\b",
        r"Total\s*Cholesterol\s+(\d+\.?\d*)\s+[HLN]\b",
        r"CHOLESTEROL\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL)\b",
        r"CHOLESTROL\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+[HLN]",
        r"CHOLESTROL\s*(?:\([^)]*\))?\s+(\d+\.?\d*)",
        r"Cholesterol\s*Total\s+(\d+\.?\d*)",
        r"Total\s*Cholesterol\s+(\d+\.?\d*)",
        # Worldwide formats
        r"Serum\s*Cholesterol\s*[:\-]\s*(\d+\.?\d*)",
        r"S\.\s*Cholesterol\s*[:\-]\s*(\d+\.?\d*)",
        r"TC\s*[:\-]\s*(\d+\.?\d*)",
        r"Cholesterol\s*[:\-]\s*(\d+\.?\d*)",
        r"T\.?\s*Cholesterol\s*[:\-]\s*(\d+\.?\d*)",
        r"CHOL\s*[:\-]\s*(\d+\.?\d*)",
        r"CHOL\s+(\d+\.?\d*)\s+[HLN]\b",
    ],
    "HDL": [
        # Existing patterns
        r"HDL\s*(?:Cholesterol)?\s*(?:\([^)]*\))?\s*[:\-]\s*(\d+\.?\d*)",
        r"HDL\s*Cholesterol\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL)\b",
        r"HDL\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL)\b",
        r"HDL\s+(\d+\.?\d*)\s+[HLN]\b",
        r"HOL\s*(?:Cholesterol)?\s+(\d+\.?\d*)",
        r"HDL\s*CHOLESTROL\s+(\d+\.?\d*)",
        r"HDL\s*(?:Cholesterol)?\s+(\d+\.?\d*)",
        # Worldwide formats
        r"HDL\s*-\s*C\s*[:\-]\s*(\d+\.?\d*)",
        r"HDL\s*Chol\s*[:\-]\s*(\d+\.?\d*)",
        r"High\s*Density\s*Lipoprotein\s*[:\-]\s*(\d+\.?\d*)",
        r"HDL\s*Cholesterol\s*[:\-]\s*(\d+\.?\d*)",
        r"HDL\s*C\s*[:\-]\s*(\d+\.?\d*)",
        r"H\.D\.L\s*[:\-]\s*(\d+\.?\d*)",
        r"HDL\s+Cholesterol\s+(\d+\.?\d*)",
        r"HDL\s*Cholesterol\s+(\d+\.?\d*)",
    ],
    "LDL": [
        # Existing patterns
        r"LDL\s*(?:Cholesterol)?\s*(?:\([^)]*\))?\s*[:\-]\s*(\d+\.?\d*)",
        r"LDL\s*Cholesterol\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL)\b",
        r"LDL\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL)\b",
        r"LDL\s+(\d+\.?\d*)\s+[HLN]\b",
        r"LOL\s*(?:Cholesterol)?\s+(\d+\.?\d*)",
        r"LDL\s*CHOLESTROL\s+[HLN]\s+(\d+\.?\d*)",
        r"LDL\s*CHOLESTROL\s+(\d+\.?\d*)",
        r"LDL\s*(?:Cholesterol)?\s+(\d+\.?\d*)",
        # Worldwide formats
        r"LDL\s*-\s*C\s*[:\-]\s*(\d+\.?\d*)",
        r"LDL\s*Chol\s*[:\-]\s*(\d+\.?\d*)",
        r"Low\s*Density\s*Lipoprotein\s*[:\-]\s*(\d+\.?\d*)",
        r"LDL\s*Cholesterol\s*[:\-]\s*(\d+\.?\d*)",
        r"LDL\s*C\s*[:\-]\s*(\d+\.?\d*)",
        r"L\.D\.L\s*[:\-]\s*(\d+\.?\d*)",
        r"LDL\s*-\s*Cholesterol\s*[:\-]\s*(\d+\.?\d*)",
        r"LDL\s+Cholesterol\s+(\d+\.?\d*)",
        r"LDL\s*Cholesterol\s+(\d+\.?\d*)",
    ],
    "Triglycerides": [
        # Existing patterns
        r"Triglycerides?\s*[:\-]\s*(\d+\.?\d*)",
        r"Triglycerides?\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL)\b",
        r"Triglycerides?\s+(\d+\.?\d*)\s+[HLN]\b",
        r"TG\s*[:\-]\s*(\d+\.?\d*)",
        r"Trig[h]?[ce]erides?\s+(\d+\.?\d*)",
        r"TRIGLYCERIDE\s+(\d+\.?\d*)",
        r"Triglycerides?\s+(\d+\.?\d*)",
        # Worldwide formats
        r"Serum\s*Triglycerides?\s*[:\-]\s*(\d+\.?\d*)",
        r"TG\s+(\d+\.?\d*)\s+[HLN]\b",
        r"TRIG\s*[:\-]\s*(\d+\.?\d*)",
        r"Triacylglycerol\s*[:\-]\s*(\d+\.?\d*)",
        r"Trig\s+(\d+\.?\d*)\s+[HLN]\b",
    ],
    "VLDL": [
        # Existing patterns
        r"VLDL\s*(?:Cholesterol)?\s*(?:\([^)]*\))?\s*[:\-]\s*(\d+\.?\d*)",
        r"VLDL\s*(?:Cholesterol)?\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL)\b",
        r"VLDL\s+(\d+\.?\d*)\s+[HLN]\b",
        r"VLOL\s*(?:Cholesterol[sl]?)?\s+(\d+\.?\d*)",
        r"VLDL\s*(?:Cholesterol)?\s+(\d+\.?\d*)",
        # Worldwide formats
        r"Very\s*Low\s*Density\s*Lipoprotein\s*[:\-]\s*(\d+\.?\d*)",
        r"VLDL\s*-\s*C\s*[:\-]\s*(\d+\.?\d*)",
        r"VLDL\s*Chol\s*[:\-]\s*(\d+\.?\d*)",
        r"VLDL\s*Cholesterol\s*[:\-]\s*(\d+\.?\d*)",
        r"V\.L\.D\.L\s*[:\-]\s*(\d+\.?\d*)",
    ],
    "Non_HDL": [
        # Existing patterns
        r"Non[\s\-]*HDL\s*(?:Cholesterol)?\s*[:\-]\s*(\d+\.?\d*)",
        r"Non[\s\-]*HDL\s*(?:Cholesterol)?\s*(?:\([^)]*\))?\s+(\d+\.?\d*)\s+(?:HIGH|LOW|NORMAL)\b",
        r"Non[\s\-]*HDL\s+(\d+\.?\d*)\s+[HLN]\b",
        r"Non[\s\-]*HOL\s*(?:Cholesterol)?\s+(\d+\.?\d*)",
        r"NON[\s\-]*HDL\s*CHOLESTEROL\s+(\d+\.?\d*)",
        r"Non[\s\-]*HDL\s*(?:Cholesterol)?\s+(\d+\.?\d*)",
        # Worldwide formats
        r"Non\s*HDL\s*Chol\s*[:\-]\s*(\d+\.?\d*)",
        r"Non\s*HDL\s*C\s*[:\-]\s*(\d+\.?\d*)",
        r"NonHDL\s*[:\-]\s*(\d+\.?\d*)",
        r"Non-HDL\s*Cholesterol\s*[:\-]\s*(\d+\.?\d*)",
    ],
}
